#' Nettoyer les listes de variables indésirables / Clean Up Unnecessary Variable Lists
#'
#' @description
#' **Français :** Dans les questionnaires Survey Solutions, lorsqu'une question de type liste est créée
#' sans spécifier de nombre maximum de réponses, le fichier de résultats peut contenir des centaines de
#' variables inutiles (par exemple, 200 colonnes ou plus) pour chaque liste. Ces colonnes ne contiennent
#' généralement que des valeurs manquantes comme `-999999999` ou `##N/A##`. Cette fonction est conçue pour
#' nettoyer ces "déchets" en supprimant toutes les colonnes qui ne contiennent que des valeurs manquantes,
#' facilitant ainsi l'analyse et réduisant l'encombrement des données.
#'
#' **English :** In Survey Solutions questionnaires, if a list-type question is created without specifying
#' a maximum number of responses, the result file may contain hundreds of unnecessary variables
#' (e.g., 200 or more columns) for each list. These columns usually contain only missing values like
#' `-999999999` or `##N/A##`. This function is designed to clean up this "clutter" by removing all columns
#' that contain only missing values, making the data easier to analyze and reducing dataset size.
#'
#' @param .data
#' **Français :** Le data frame principal à nettoyer (généralement le tableau de résultats) ou un data frame
#' de nomenclature si `data` est fourni.
#' **English :** The main data frame to clean (usually the result table) or a nomenclature data frame
#' if `data` is provided.
#'
#' @param data
#' **Français :** (Optionnel) Un ou plusieurs data frames de résultats servant à identifier les colonnes à
#' supprimer dans la nomenclature fournie en `data`. Si `data` n'est pas `NULL`, `.data` est interprété comme
#' une nomenclature.
#' **English :** (Optional) One or more result data frames used to identify columns to be removed in the
#' nomenclature provided in `.data`. If `data` is not `NULL`, `.data` is interpreted as a nomenclature.
#'
#' @param variable_name_col
#' **Français :** Nom de la colonne dans la nomenclature correspondant aux noms de variables (par défaut `"variable_name"`).
#' **English :** Name of the column in the nomenclature corresponding to variable names (default `"variable_name"`).
#'
#' @return
#' **Français :** Un data frame nettoyé, soit le tableau de résultats sans les colonnes indésirables,
#' soit la nomenclature sans les lignes correspondant aux variables supprimées.
#' **English :** A cleaned data frame, either the result table without unnecessary columns, or the
#' nomenclature without rows corresponding to removed variables.
#'
#' @details
#' **Français :** La fonction nettoie un tableau de résultats en supprimant les colonnes contenant uniquement
#' des valeurs indésirables (`-999999999`, `##N/A##`, ou `NA`). Si un data frame de nomenclature est fourni,
#' la fonction filtre également la nomenclature pour supprimer les lignes correspondant aux colonnes
#' éliminées du tableau de résultats. Cette méthode est particulièrement utile pour les questionnaires
#' Survey Solutions où des listes volumineuses de colonnes inutiles peuvent être générées par oubli de
#' limite de réponses.
#'
#' **English :** The function cleans a result table by removing columns containing only undesirable values
#' (`-999999999`, `##N/A##`, or `NA`). If a nomenclature data frame is provided, the function also filters
#' the nomenclature to remove rows corresponding to removed columns in the result table. This method is
#' particularly useful for Survey Solutions questionnaires, where large lists of unnecessary columns
#' can be generated by omitting response limits.
#'
#' @examples
#' \dontrun{
#' # Exemple en français
#' # Nettoyer un tableau de résultats uniquement
#' results_clean <- ESS_2024_labeled %>%
#'   clean_lists()
#'
#' # Nettoyer une nomenclature en utilisant un tableau de résultats
#' nomenclature_clean <- nomenclature_df %>%
#'   clean_lists(data = ESS_2024_labeled)
#'
#' # Nettoyer une nomenclature avec plusieurs tableaux de résultats
#' nomenclature_clean <- nomenclature_df %>%
#'   clean_lists(data = list(ESS_2024_labeled, ESS_2024_Roster_AvantApres))
#'
#' # English example
#' # Clean a result table only
#' results_clean <- ESS_2024_labeled %>%
#'   clean_lists()
#'
#' # Clean a nomenclature using a result table
#' nomenclature_clean <- nomenclature_df %>%
#'   clean_lists(data = ESS_2024_labeled)
#'
#' # Clean a nomenclature with multiple result tables
#' nomenclature_clean <- nomenclature_df %>%
#'   clean_lists(data = list(ESS_2024_labeled, ESS_2024_Roster_AvantApres))
#' }
#'
#' @export
clean_lists <- function(.data, data = NULL, variable_name_col = "variable_name") {
  # Vérifier que .data est un data frame
  if (!is.data.frame(.data)) {
    stop("Le paramètre .data doit être un data frame.")
  }

  # Déterminer si .data est une nomenclature ou un tableau de résultats
  if (variable_name_col %in% names(.data)) {
    # .data est une nomenclature
    if (is.null(data)) {
      stop("Veuillez fournir le(s) data frame(s) de résultats via le paramètre 'data' pour nettoyer la nomenclature.")
    }

    # Identifier les colonnes à supprimer à partir des data frames de résultats
    if (is.list(data) && all(sapply(data, is.data.frame))) {
      # Si 'data' est une liste de data frames
      all_cols_to_remove <- unique(unlist(lapply(data, identify_cols_to_remove)))
    } else if (is.data.frame(data)) {
      # Si 'data' est un data frame unique
      all_cols_to_remove <- identify_cols_to_remove(data)
    } else {
      stop("Le paramètre 'data' doit être un data frame ou une liste de data frames.")
    }

    # Nettoyer la nomenclature
    nomenclature_clean <- .data %>%
      filter(!(.data[[variable_name_col]] %in% all_cols_to_remove))

    return(nomenclature_clean)
  } else {
    # .data est un tableau de résultats
    # Identifier les colonnes à supprimer
    all_cols_to_remove <- identify_cols_to_remove(.data)

    # Nettoyer le tableau de résultats
    data_clean <- .data %>%
      select(-all_of(all_cols_to_remove))

    return(data_clean)
  }
}
